version: '3.9'
services:
  postgres:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '65432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  lead-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
